---
title: "Model_building_2"
author: "Annie Cohen"
date: "4/25/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(tidyverse)
library(lubridate)
library(TSA)
library(RCurl)
library(forecast)
```

```{r}
# pulling the data from the Los Angeles County GitHub
casedata <- read.csv(text = getURL("https://raw.githubusercontent.com/datadesk/california-coronavirus-data/master/latimes-county-totals.csv")) %>%
  filter(county == "Los Angeles") %>%
  mutate(date = date(date), month = month(date)) %>%
  map_df(rev) %>%
  filter(!is.na(new_confirmed_cases) & between(date, date("2020-04-01"),date("2021-03-31")))

# creating the time series
case.ts <- ts(casedata$new_confirmed_cases, start = 1,  frequency = 1)

# averaging dec 25th and 26th
case.ts[269] <- 14711
case.ts[270] <- 14712

# april 1 - jul 14
case.ts.1.1 <- ts(case.ts[1:105], start = 1, frequency = 1)
# jul 15 - sep 30
case.ts.1.2 <- ts(case.ts[106:183], start = 1, frequency = 1)

# oct 1 - dec 20
case.ts.2.1 <- ts(case.ts[184:264], start = 1, frequency = 1)
# dec 21 - mar 31
case.ts.2.2 <- ts(case.ts[265:365], start = 1, frequency = 1)
```

## July 15 to September 30

```{r}
eacf(diff(trans.ts.1.2))

arima.ts.1.2.2 <- arima(trans.ts.1.2, order = c(1,1,1))

acf(arima.ts.1.2.2$residuals)

diff.trans.1.2 <- ts(diff(trans.ts.1.2, lag = 7, differences = 1), frequency = 7)
eacf(diff.trans.1.2)
arima.1.2 <- arima(diff.trans.1.2, order = c(1,0,0), seasonal = list(order = c(0,1,1), period = 7))

acf(arima.1.2$residuals)

runs(arima.1.2$residuals)

shapiro.test(arima.1.2$residuals)

Box.test(arima.1.2$residuals, type = "Ljung-Box")

```

```{r}
trans.seasonal.ts.1.2 <- ts(log(case.ts.1.2), frequency = 7)
trans.ts.1.2 <- ts(log(case.ts.1.2))

plot(trans.seasonal.ts.1.2, type = "l")
points(trans.seasonal.ts.1.2, pch = as.vector(season(trans.seasonal.ts.1.1)), cex = 0.8, col = "blue")

res <- armasubsets(trans.ts.1.2, nar = 7, nma = 7)
plot(res)
eacf(trans.ts.1.2)
auto.arima(trans.seasonal.ts.1.2, max.P = 5, max.Q = 5)
auto.arima(trans.ts.1.2, max.P = 5, max.Q = 5)

arima.seasonal.ts.1.2.2 <-arima(trans.seasonal.ts.1.2, order = c(0,0,2), seasonal = list(order = c(1,0,1), period = 7))
arima.seasonal.ts.1.2 <- arima(trans.seasonal.ts.1.2, order = c(1,0,0), seasonal = list(order = c(0,1,1), period = 7))
arima.ts.1.2 <- arima(trans.ts.1.2, order = c(0,1,2))
arima.ts.1.2.2 <- arima(trans.ts.1.2, order = c(0,0,1))

Box.test(arima.seasonal.ts.1.2$residuals, type = "Ljung-Box")
Box.test(arima.seasonal.ts.1.2.2$residuals, type = "Ljung-Box")
Box.test(arima.ts.1.2$residuals, type = "Ljung-Box")
Box.test(arima.ts.1.2.2$residuals, type = "Ljung-Box")

shapiro.test(arima.seasonal.ts.1.2$residuals)
shapiro.test(arima.seasonal.ts.1.2.2$residuals)
shapiro.test(arima.ts.1.2$residuals)
shapiro.test(arima.ts.1.2.2$residuals)

runs(arima.seasonal.ts.1.2$residuals)
runs(arima.seasonal.ts.1.2.2$residuals)
runs(arima.ts.1.2$residuals)
runs(arima.ts.1.2.2$residuals)

par(mfrow = c(2,2))

acf(arima.seasonal.ts.1.2.2$residuals)
acf(arima.seasonal.ts.1.2$residuals)
acf(arima.ts.1.2$residuals)
acf(arima.ts.1.2.2$residuals)

pacf(arima.seasonal.ts.1.2.2$residuals)
pacf(arima.seasonal.ts.1.2$residuals)
pacf(arima.ts.1.2$residuals)
pacf(arima.ts.1.2.2$residuals)

plot(arima.seasonal.ts.1.2.2$residuals, type = "o", pch = 20)
abline(a=0,b=0,lty=2,col="blue")
plot(arima.seasonal.ts.1.2$residuals, type = "o", pch = 20)
abline(a=0,b=0,lty=2,col="blue")
plot(arima.ts.1.2$residuals, type = "o", pch = 20)
abline(a=0,b=0,lty=2,col="blue")
plot(arima.ts.1.2.2$residuals, type = "o", pch = 20)
abline(a=0,b=0,lty=2,col="blue")

hist(arima.seasonal.ts.1.2.2$residuals)
hist(arima.seasonal.ts.1.2$residuals)
hist(arima.ts.1.2$residuals)
hist(arima.ts.1.2.2$residuals)

qqnorm(arima.seasonal.ts.1.2.2$residuals)
qqline(arima.seasonal.ts.1.2.2$residuals)

qqnorm(arima.seasonal.ts.1.2$residuals)
qqline(arima.seasonal.ts.1.2$residuals)

qqnorm(arima.ts.1.2$residuals)
qqline(arima.ts.1.2$residuals)

qqnorm(arima.ts.1.2.2$residuals)
qqline(arima.ts.1.2.2$residuals)
```
