---
title: "Model Building 4"
author: "Lian Morales"
date: "4/26/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(tidyverse)
library(lubridate)
library(TSA)
library(RCurl)
library(forecast)
```

```{r}
# pulling the data from the Los Angeles County GitHub
casedata <- read.csv(text = getURL("https://raw.githubusercontent.com/datadesk/california-coronavirus-data/master/latimes-county-totals.csv")) %>%
  filter(county == "Los Angeles") %>%
  mutate(date = date(date), month = month(date)) %>%
  map_df(rev) %>%
  filter(!is.na(new_confirmed_cases) & between(date, date("2020-04-01"),date("2021-03-31")))

# creating the time series
case.ts <- ts(casedata$new_confirmed_cases, start = 1,  frequency = 1)

# averaging dec 25th and 26th
case.ts[269] <- 14711
case.ts[270] <- 14712

# dec 21 - mar 31
case.ts.2.2 <- ts(case.ts[265:365], start = 1, frequency = 1)

```

## December 21 - March 31

```{r}
set.seed(13)
# transform data October 1 - December 20 to lambda + add seasonality
trans.seasonal.ts.2.2  <- ts(case.ts.2.2^0.2, frequency = 7,start = c(1,5))
seasonal.ts.2.2  <- ts(case.ts.2.2, frequency = 7,start = c(1,5))
trans.ts.2.2 <- ts(case.ts.2.2^0.2)
# plot ts of seasonal data
week. <- season(seasonal.ts.2.2)
plot(seasonal.ts.2.2, ylab = "Number of New Cases", xlab = "Week", main = "COVID-19 new case data in Los Angeles county \nDecember 21 to March 31")
points(seasonal.ts.2.2, pch = as.vector(week.), col = "blue", cex = 0.8)

week. <- season(trans.seasonal.ts.2.2)
plot(trans.seasonal.ts.2.2, ylab = "Number of New Cases", xlab = "Week", main = "Lamda-transformed COVID-19 new case data in Los Angeles county \nDecember 21 to March 31")
points(trans.seasonal.ts.2.2, pch = as.vector(week.), col = "blue", cex = 0.8)

# acf of transformed data 
acf(seasonal.ts.2.2, main = "ACF of LA County COVID-19 data \nDecember 21 to March 31")
# pacf of transformed data
pacf(seasonal.ts.2.2, main = "PACF of LA County COVID-19 data \nDecember 21 to March 31")

```

```{r}

# best subsets ARMA approach
eacf(trans.seasonal.ts.2.2)
eacf(diff(trans.seasonal.ts.2.2, lag = 7))
plot(armasubsets(y=diff(trans.ts.2.2,lag=7), nar= 7, nma = 13, y.name = "test", ar.method = 'ols'))
auto.arima(trans.seasonal.ts.2.2)
auto.arima(trans.ts.2.2)

```

ARIMA(3,0,0)x(0,1,1) # dif of arma subset
ARIMA(3,1,2) # arima sim
ARIMA(0,1,3) # arima sim

## Completing analysis with suggested models
```{r}

# create aimra models for seasonal and transformed data
arima.seasonal.ts.2.2.1 <- arima(trans.ts.2.2, order = c(3,0,0), seasonal = list(order = c(0,1,1), period = 7))
arima.ts.2.2.2 <- arima(trans.seasonal.ts.2.2, order = c(3,1,2))
arima.ts.2.2.3 <- arima(trans.ts.2.2, order = c(0,1,3))
```

```{r}
par(mfrow = c(3,2))
# plot residuals
plot(rstandard(arima.seasonal.ts.2.2.1),type = "o", pch=20)
abline(h=0,lty=2,col="blue")
plot(rstandard(arima.ts.2.2.2),type = "o", pch=20)
abline(h=0,lty=2,col="blue")
plot(rstandard(arima.ts.2.2.3),type = "o", pch=20)
abline(h=0,lty=2,col="blue")

```
```{r}
# AIC
arima.seasonal.ts.2.2.1$aic
arima.ts.2.2.2$aic
arima.ts.2.2.3$aic
```


```{r}
# residual tests

# check for correlation of error terms
Box.test(rstandard(arima.seasonal.ts.2.2.1), type = "Ljung-Box")
Box.test(rstandard(arima.ts.2.2.2), type = "Ljung-Box")
Box.test(rstandard(arima.ts.2.2.3), type = "Ljung-Box")
# check for normality of error terms
shapiro.test(rstandard(arima.seasonal.ts.2.2.1))
shapiro.test(rstandard(arima.ts.2.2.2))
shapiro.test(rstandard(arima.ts.2.2.3))
# check for independence of error terms
runs(rstandard(arima.seasonal.ts.2.2.1))
runs(rstandard(arima.ts.2.2.2))
runs(rstandard(arima.ts.2.2.3))

```

## Visualize residuals 
```{r}
layout(matrix(c(1,2,3,4,5,0), nrow = 3, ncol = 2, byrow = TRUE))

acf(arima.seasonal.ts.2.2.1$residuals)
acf(arima.ts.2.2.2$residuals)
acf(arima.ts.2.2.3$residuals)
 
 
# pacf of seasonal and transformed residuals
pacf(arima.seasonal.ts.2.2.1$residuals)
pacf(arima.ts.2.2.2$residuals)
pacf(arima.ts.2.2.3$residuals)


# Histogram of residuals
hist(arima.seasonal.ts.2.2.1$residuals)
hist(arima.ts.2.2.2$residuals)
hist(arima.ts.2.2.3$residuals)

# qqnorm plots of residuals
qqnorm(rstandard(arima.seasonal.ts.2.2.1))
qqline(rstandard(arima.seasonal.ts.2.2.1))

qqnorm(rstandard(arima.ts.2.2.2))
qqline(rstandard(arima.ts.2.2.2))

qqnorm(rstandard(arima.ts.2.2.3))
qqline(rstandard(arima.ts.2.2.3))

```
## Forecasting

```{r}
fit.1 <- Arima(trans.ts.2.2, order = c(3,0,0), seasonal = list(order = c(0,1,1), period = 7))
fit.1.ts <- ts(fit.1$fitted, frequency = 7, start = c(1,5))
fit.2 <- Arima(trans.seasonal.ts.2.2, order = c(3,1,2))

par(mfrow = c(2,1))
plot(trans.ts.2.2, ylab = "cases^0.2", main = "AR(3)xIMA(1,1)[7] accuracy")
lines(fit.1$fitted, col = "lightblue4")
plot(trans.seasonal.ts.2.2, ylab = "cases^0.2", main = "ARIMA(3,1,2) accuracy")
lines(fit.2$fitted, col = "darkorange")

testdata <- read.csv(text = getURL("https://raw.githubusercontent.com/datadesk/california-coronavirus-data/master/latimes-county-totals.csv")) %>%
  filter(county == "Los Angeles") %>%
  mutate(date = date(date), month = month(date)) %>%
  map_df(rev) %>%
  filter(!is.na(new_confirmed_cases) & between(date, date("2021-04-01"),date("2021-04-30")))

testdata.ts <- ts((testdata$new_confirmed_cases)^0.2, frequency = 7, start = c(16,1))
par(mfrow = c(1,1))
plot(forecast(fit.1.ts,h=30), col = "orange", main = "Forecasts from ARIMA(3,1,2)",ylab="Number of Cases ^ 0.2", xlab = "Weeks")
lines(trans.seasonal.ts.2.2)
lines(testdata.ts, col = "red")

```
